document.write('<head>')
document.write('  <link rel="stylesheet" href="style.css">')
document.write('  <script src="main.js"></script>')
document.write('</head>')
document.write('<p style="color: white">')
document.write('  <a href="cf.html">CF</a>')
document.write('   | ')
document.write('   <a href="nl.html">NL</a>')
document.write('</p>')